import {Dimensions, StyleSheet} from 'react-native';
import {globalfonts} from '../../../assets/FrontExport/Frontexport';
import {global} from '../../Components/GlobalComponent/GlobalStyle';
const {height, width} = Dimensions.get('window');

export default styles = StyleSheet.create({
  imgContainer:{
    height: '90%',
    width: '90%',
    justifyContent: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'center',
    borderRadius: 12,
  },
  addedBtn: {
    fontSize: 15,
    color: '#000',
    fontFamily: globalfonts.font5,
  },
  addBtn: {
    fontSize: 15,
    color: '#000',
    fontFamily: globalfonts.font5,
  },
  noBookAvaliable: {
    color: global.sandColor,
    fontSize: 25,
    fontFamily: globalfonts.font,
    marginTop: '20%',
    textDecorationLine: 'underline',
    alignSelf: 'center',
  },
  addBtnCont: {
    position: 'absolute',
    bottom: 10,
    right: 10,
  },
  profilePhotoText: {
    alignSelf: 'center',
    fontSize: width / 30,
    // justifyContent: 'center',
    // alignContent:"center"
  },
  booksName: {
    width: 210,
    fontSize: 20,
    color: '#000',
    marginHorizontal: '2%',
    fontFamily: globalfonts.font5,
  },
  removeBtn: {
    height: height / 25,
    width: width / 6,
    // position: 'absolute',
    backgroundColor: global.lightgray,
    // right: 10,
    // bottom: 10,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
  },
  addBtn: {
    height: height / 25,
    width: width / 7,
    // position: 'absolute',
    backgroundColor: global.sandColor,
    // right: 10,
    // bottom: 1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
  },
  editionCont: {flexDirection: 'row', marginTop: '1%', flexDirection: 'row'},
  booksHead: {
    fontSize: 14,
    color: '#000',
    fontWeight: '400',
    marginHorizontal: '2%',
    fontFamily: globalfonts.font5,
  },
  bookstxt: {
    fontSize: 15,
    color: '#000',
    marginHorizontal: '2%',
    fontFamily: globalfonts.font5,
  },
  productInfo: {
    flex: 4,
    height: '100%',
    paddingVertical: '1%',
  },
  productPhoto: {
    flex: 2,
    height: '100%',
    width: '50%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  allBookContainer: {
    height: height / 5.5,
    width: width - 20,
    backgroundColor: '#fafafa',
    borderRadius: 10,
    marginVertical: '1.5%',
    flexDirection: 'row',
    elevation: 1,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  ParentContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  headerCont: {
    backgroundColor: 'rgba(26,54,54,0.5)',
    height: 70,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  headerText: {
    color: 'white',
    fontSize: 20,
  },
  content: {
    flex: 1,
    color: '#000',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  topcontent: {
    color: '#000',
    flexDirection: 'row',
  },
  inputfield: {
    width: width - 100,
    backgroundColor: '#fff',
    height: height / 24,
    borderRadius: 10,
    color: global.bgColor,
    fontSize: 15,
    paddingHorizontal: 20,
    elevation: 20,
  },
  searchfield: {
    flexDirection: 'row',
    alignItems: 'center',
    width: width - 100,
    backgroundColor: '#fff',
    height: height / 24,
    borderRadius: 10,
    color: global.bgColor,
    fontSize: 15,
    paddingHorizontal: 5,
    elevation: 20,
    right: 3,
  },
  bookContainer: {
    height: height / 3.5,
    width: width / 2.2,
    borderRadius: 10,
    borderWidth: 1,
    margin: '2%',
    overflow: 'hidden',
  },
  newBookContainer: {
    height: height / 4,
    width: width - 20,
    backgroundColor: global.sandColor,
    borderRadius: 10,
    borderColor: global.bgColor,
    borderWidth: 1,
    marginHorizontal: '1%',
    elevation: 10,
    marginVertical: 20,
  },
  topimg: {height: height / 5, width: '100%'},
  BookInfo: {
    color: '#000',
    fontSize: 18,
    fontWeight: '500',
    paddingHorizontal: '5%',
  },
  BookDetails: {
    color: '#000',
    fontSize: 16,
    fontWeight: '300',
    paddingHorizontal: '5%',
  },
  BookDiscount: {
    color: '#000',
    fontSize: 19,
    fontWeight: '600',
    paddingHorizontal: '5%',
  },
  newArival: {
    color: '#fff',
    fontSize: 30,
    marginHorizontal: 10,
    fontFamily: globalfonts.font,
    backgroundColor: global.thirdColor,
    borderRadius: 6,
    paddingHorizontal: 10,
    elevation: 10,
  },
  userProfile: {
    height: height / 23,
    width: width / 10.5,
    backgroundColor: global.bgColor,
    borderRadius: 50,
    borderColor: global.sandColor,
    borderWidth: 1,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  cartBadge: {
    color: '#fff',
    position: 'absolute',
    right: 5,
    top: 10,
    backgroundColor: global.sandColor,
    color: global.bgColor,
  },
  bookChooseCatCont: {flexDirection: 'row'},
  catBtnCont: {
    marginVertical: '1.5%',
    borderColor: global.bgColor,
    marginLeft: '2%',
    borderWidth: 1,
    paddingHorizontal: '2%',
    paddingVertical: '1%',
    borderRadius: 20,
  },
  allbookcatBtnCont: {
    marginVertical: '1.5%',
    borderColor: global.bgColor,
    marginLeft: '2%',
    borderWidth: 1,
    paddingHorizontal: '2%',
    paddingVertical: '1%',
    borderRadius: 20,
  },
  all: {fontSize: 18, color: global.bgColor, fontFamily: globalfonts.font4},
});
